import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Copy, Download, Terminal, Info, CaretDown, CheckCircle, Warning } from '@phosphor-icons/react'
import { toast } from 'sonner'
import { Toaster } from '@/components/ui/sonner'

function App() {
  const [repoName, setRepoName] = useState('')
  const [createBackup, setCreateBackup] = useState(true)
  const [customBranchName, setCustomBranchName] = useState('new_branch')
  const [showExplanations, setShowExplanations] = useState(false)
  const [generatedScript, setGeneratedScript] = useState('')
  const [isGenerated, setIsGenerated] = useState(false)

  const sanitizeRepoName = (name: string) => {
    return name.replace(/[^a-zA-Z0-9-_]/g, '').slice(0, 100)
  }

  const sanitizeBranchName = (name: string) => {
    return name.replace(/[^a-zA-Z0-9-_]/g, '').slice(0, 100)
  }

  const handleRepoNameChange = (value: string) => {
    const sanitized = sanitizeRepoName(value)
    setRepoName(sanitized)
    if (sanitized !== value) {
      toast.warning('Repository name was sanitized (only letters, numbers, hyphens, and underscores allowed)')
    }
  }

  const handleBranchNameChange = (value: string) => {
    const sanitized = sanitizeBranchName(value)
    setCustomBranchName(sanitized)
    if (sanitized !== value) {
      toast.warning('Branch name was sanitized (only letters, numbers, hyphens, and underscores allowed)')
    }
  }

  const generateScript = () => {
    if (!repoName.trim()) {
      toast.error('Please enter a repository name')
      return
    }

    const script = `#!/bin/bash
# Git History Cleaner Script for: ${repoName}
# Generated by Git History Cleaner Tool

${createBackup ? `# Create backup first (recommended)
cp -r ${repoName} ${repoName}-backup
` : ''}# Navigate to repository
cd ${repoName}

# Create a completely new branch with no history
git checkout --orphan ${customBranchName}

# Add all your files
git add -A

# Commit everything with a new initial message
git commit -m "Initial commit"

# Delete the main branch
git branch -D main

# Rename current branch to main
git branch -m main

# Force push to remote
git push -f origin main`

    setGeneratedScript(script)
    setIsGenerated(true)
    toast.success('Script generated successfully!')
  }

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(generatedScript)
      toast.success('Script copied to clipboard!')
    } catch (err) {
      toast.error('Failed to copy script')
    }
  }

  const downloadScript = () => {
    const blob = new Blob([generatedScript], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `clear-history-${repoName}.sh`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    toast.success('Script downloaded!')
  }

  const commandExplanations = [
    {
      command: 'cp -r repo repo-backup',
      explanation: 'Creates a complete backup copy of your repository folder before making any changes'
    },
    {
      command: 'cd repo',
      explanation: 'Navigates into the repository directory to perform git operations'
    },
    {
      command: 'git checkout --orphan new_branch',
      explanation: 'Creates a new branch with no commit history - like starting fresh'
    },
    {
      command: 'git add -A',
      explanation: 'Stages all current files (but without their history) for the new commit'
    },
    {
      command: 'git commit -m "Initial commit"',
      explanation: 'Creates the first and only commit in the new clean history'
    },
    {
      command: 'git branch -D main',
      explanation: 'Deletes the old main branch with all its history'
    },
    {
      command: 'git branch -m main',
      explanation: 'Renames the new clean branch to "main"'
    },
    {
      command: 'git push -f origin main',
      explanation: 'Force pushes the clean history to overwrite the remote repository'
    }
  ]

  return (
    <div className="min-h-screen bg-background p-4 md:p-8">
      <Toaster />
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center space-y-2">
          <h1 className="text-3xl md:text-4xl font-bold text-foreground">Git History Cleaner</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Generate safe, customizable scripts to clear git repository history while preserving your current files
          </p>
        </div>

        <Alert>
          <Warning className="h-4 w-4" />
          <AlertDescription>
            <strong>Important:</strong> This tool generates scripts that permanently delete git history. 
            Always create backups and understand the commands before executing.
          </AlertDescription>
        </Alert>

        <div className="grid gap-8 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Terminal className="h-5 w-5" />
                Script Configuration
              </CardTitle>
              <CardDescription>
                Customize your git history clearing script with safety options
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="repo-name">Repository Name</Label>
                <Input
                  id="repo-name"
                  placeholder="my-awesome-repo"
                  value={repoName}
                  onChange={(e) => handleRepoNameChange(e.target.value)}
                  className="font-mono"
                />
                {repoName && (
                  <p className="text-sm text-muted-foreground">
                    Script will be generated for: <code className="font-mono bg-muted px-1 py-0.5 rounded">{repoName}</code>
                  </p>
                )}
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-1">
                    <Label htmlFor="create-backup">Create Backup</Label>
                    <p className="text-sm text-muted-foreground">Recommended: Creates a full backup before clearing history</p>
                  </div>
                  <Switch
                    id="create-backup"
                    checked={createBackup}
                    onCheckedChange={setCreateBackup}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="branch-name">Temporary Branch Name</Label>
                  <Input
                    id="branch-name"
                    value={customBranchName}
                    onChange={(e) => handleBranchNameChange(e.target.value)}
                    className="font-mono"
                  />
                  <p className="text-sm text-muted-foreground">
                    Name for the temporary branch used during the process
                  </p>
                </div>
              </div>

              <Button 
                onClick={generateScript}
                className="w-full"
                size="lg"
                disabled={!repoName.trim()}
              >
                Generate Script
              </Button>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle>Generated Script</CardTitle>
                  <CardDescription>
                    {isGenerated ? 'Ready to copy or download' : 'Configure options and generate your script'}
                  </CardDescription>
                </div>
                {isGenerated && (
                  <div className="flex gap-2">
                    <Button variant="outline" size="sm" onClick={copyToClipboard}>
                      <Copy className="h-4 w-4" />
                    </Button>
                    <Button variant="outline" size="sm" onClick={downloadScript}>
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                )}
              </div>
            </CardHeader>
            <CardContent>
              {isGenerated ? (
                <Textarea
                  value={generatedScript}
                  readOnly
                  className="font-mono text-sm min-h-[300px] resize-none"
                />
              ) : (
                <div className="min-h-[300px] flex items-center justify-center border-2 border-dashed border-border rounded-lg">
                  <div className="text-center space-y-2">
                    <Terminal className="h-12 w-12 text-muted-foreground mx-auto" />
                    <p className="text-muted-foreground">Your generated script will appear here</p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        <Card>
          <Collapsible open={showExplanations} onOpenChange={setShowExplanations}>
            <CollapsibleTrigger asChild>
              <CardHeader className="cursor-pointer hover:bg-muted/50 transition-colors">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Info className="h-5 w-5" />
                    <CardTitle>Command Explanations</CardTitle>
                  </div>
                  <CaretDown className={`h-5 w-5 transition-transform ${showExplanations ? 'rotate-180' : ''}`} />
                </div>
                <CardDescription>
                  Learn what each git command does in plain English
                </CardDescription>
              </CardHeader>
            </CollapsibleTrigger>
            <CollapsibleContent>
              <CardContent>
                <div className="space-y-4">
                  {commandExplanations.map((item, index) => (
                    <div key={index} className="flex gap-4 p-4 bg-muted/50 rounded-lg">
                      <div className="flex-shrink-0">
                        <CheckCircle className="h-5 w-5 text-primary mt-0.5" />
                      </div>
                      <div className="space-y-1">
                        <code className="font-mono text-sm bg-background px-2 py-1 rounded border">
                          {item.command}
                        </code>
                        <p className="text-sm text-muted-foreground">
                          {item.explanation}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
                <Alert className="mt-4">
                  <Warning className="h-4 w-4" />
                  <AlertDescription>
                    <strong>Remember:</strong> The force push (<code className="font-mono">git push -f</code>) permanently 
                    overwrites the remote repository history. Make sure you have backups and team approval before running this script.
                  </AlertDescription>
                </Alert>
              </CardContent>
            </CollapsibleContent>
          </Collapsible>
        </Card>
      </div>

      <footer className="max-w-4xl mx-auto mt-8 py-6 border-t border-border text-center text-sm text-muted-foreground">
        <p>
          Made with ❤️ by{' '}
          <a 
            href="https://x.com/acolombiadedev" 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-foreground hover:underline"
          >
            @acolombiadev
          </a>
        </p>
        <p className="mt-1">
          Open source under the{' '}
          <a 
            href="./LICENSE" 
            target="_blank" 
            rel="noopener noreferrer"
            className="text-foreground hover:underline"
          >
            MIT License
          </a>
        </p>
      </footer>
    </div>
  )
}

export default App